// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchRequest.proto

package com.example;

public final class SearchRequestProto {
  private SearchRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string keyword = 1;</code>
     */
    java.lang.String getKeyword();
    /**
     * <code>string keyword = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeywordBytes();

    /**
     * <code>int32 page = 2;</code>
     */
    int getPage();

    /**
     * <code>int32 size = 3;</code>
     */
    int getSize();

    /**
     * <pre>
     * 4 to 9 x
     * </pre>
     *
     * <code>.SearchRequest.Sort sort = 10;</code>
     */
    int getSortValue();
    /**
     * <pre>
     * 4 to 9 x
     * </pre>
     *
     * <code>.SearchRequest.Sort sort = 10;</code>
     */
    com.example.SearchRequestProto.SearchRequest.Sort getSort();
  }
  /**
   * Protobuf type {@code SearchRequest}
   */
  public  static final class SearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SearchRequest)
      SearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      keyword_ = "";
      sort_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              keyword_ = s;
              break;
            }
            case 16: {

              page_ = input.readInt32();
              break;
            }
            case 24: {

              size_ = input.readInt32();
              break;
            }
            case 80: {
              int rawValue = input.readEnum();

              sort_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.SearchRequestProto.internal_static_SearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.SearchRequestProto.internal_static_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.SearchRequestProto.SearchRequest.class, com.example.SearchRequestProto.SearchRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code SearchRequest.Sort}
     */
    public enum Sort
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ASC = 0;</code>
       */
      ASC(0),
      /**
       * <code>DESC = 1;</code>
       */
      DESC(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ASC = 0;</code>
       */
      public static final int ASC_VALUE = 0;
      /**
       * <code>DESC = 1;</code>
       */
      public static final int DESC_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sort valueOf(int value) {
        return forNumber(value);
      }

      public static Sort forNumber(int value) {
        switch (value) {
          case 0: return ASC;
          case 1: return DESC;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sort>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sort> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sort>() {
              public Sort findValueByNumber(int number) {
                return Sort.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.SearchRequestProto.SearchRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sort[] VALUES = values();

      public static Sort valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sort(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SearchRequest.Sort)
    }

    public static final int KEYWORD_FIELD_NUMBER = 1;
    private volatile java.lang.Object keyword_;
    /**
     * <code>string keyword = 1;</code>
     */
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyword_ = s;
        return s;
      }
    }
    /**
     * <code>string keyword = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <code>int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>int32 size = 3;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int SORT_FIELD_NUMBER = 10;
    private int sort_;
    /**
     * <pre>
     * 4 to 9 x
     * </pre>
     *
     * <code>.SearchRequest.Sort sort = 10;</code>
     */
    public int getSortValue() {
      return sort_;
    }
    /**
     * <pre>
     * 4 to 9 x
     * </pre>
     *
     * <code>.SearchRequest.Sort sort = 10;</code>
     */
    public com.example.SearchRequestProto.SearchRequest.Sort getSort() {
      @SuppressWarnings("deprecation")
      com.example.SearchRequestProto.SearchRequest.Sort result = com.example.SearchRequestProto.SearchRequest.Sort.valueOf(sort_);
      return result == null ? com.example.SearchRequestProto.SearchRequest.Sort.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeywordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keyword_);
      }
      if (page_ != 0) {
        output.writeInt32(2, page_);
      }
      if (size_ != 0) {
        output.writeInt32(3, size_);
      }
      if (sort_ != com.example.SearchRequestProto.SearchRequest.Sort.ASC.getNumber()) {
        output.writeEnum(10, sort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeywordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, keyword_);
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      if (sort_ != com.example.SearchRequestProto.SearchRequest.Sort.ASC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, sort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.SearchRequestProto.SearchRequest)) {
        return super.equals(obj);
      }
      com.example.SearchRequestProto.SearchRequest other = (com.example.SearchRequestProto.SearchRequest) obj;

      if (!getKeyword()
          .equals(other.getKeyword())) return false;
      if (getPage()
          != other.getPage()) return false;
      if (getSize()
          != other.getSize()) return false;
      if (sort_ != other.sort_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeyword().hashCode();
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (37 * hash) + SORT_FIELD_NUMBER;
      hash = (53 * hash) + sort_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.SearchRequestProto.SearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.SearchRequestProto.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.SearchRequestProto.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.SearchRequestProto.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.SearchRequestProto.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SearchRequest)
        com.example.SearchRequestProto.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.SearchRequestProto.internal_static_SearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.SearchRequestProto.internal_static_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.SearchRequestProto.SearchRequest.class, com.example.SearchRequestProto.SearchRequest.Builder.class);
      }

      // Construct using com.example.SearchRequestProto.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        keyword_ = "";

        page_ = 0;

        size_ = 0;

        sort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.SearchRequestProto.internal_static_SearchRequest_descriptor;
      }

      @java.lang.Override
      public com.example.SearchRequestProto.SearchRequest getDefaultInstanceForType() {
        return com.example.SearchRequestProto.SearchRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.SearchRequestProto.SearchRequest build() {
        com.example.SearchRequestProto.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.SearchRequestProto.SearchRequest buildPartial() {
        com.example.SearchRequestProto.SearchRequest result = new com.example.SearchRequestProto.SearchRequest(this);
        result.keyword_ = keyword_;
        result.page_ = page_;
        result.size_ = size_;
        result.sort_ = sort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.SearchRequestProto.SearchRequest) {
          return mergeFrom((com.example.SearchRequestProto.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.SearchRequestProto.SearchRequest other) {
        if (other == com.example.SearchRequestProto.SearchRequest.getDefaultInstance()) return this;
        if (!other.getKeyword().isEmpty()) {
          keyword_ = other.keyword_;
          onChanged();
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (other.sort_ != 0) {
          setSortValue(other.getSortValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.SearchRequestProto.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.SearchRequestProto.SearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object keyword_ = "";
      /**
       * <code>string keyword = 1;</code>
       */
      public java.lang.String getKeyword() {
        java.lang.Object ref = keyword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string keyword = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeywordBytes() {
        java.lang.Object ref = keyword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string keyword = 1;</code>
       */
      public Builder setKeyword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string keyword = 1;</code>
       */
      public Builder clearKeyword() {
        
        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }
      /**
       * <code>string keyword = 1;</code>
       */
      public Builder setKeywordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keyword_ = value;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>int32 page = 2;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>int32 page = 2;</code>
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page = 2;</code>
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>int32 size = 3;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 3;</code>
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 3;</code>
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private int sort_ = 0;
      /**
       * <pre>
       * 4 to 9 x
       * </pre>
       *
       * <code>.SearchRequest.Sort sort = 10;</code>
       */
      public int getSortValue() {
        return sort_;
      }
      /**
       * <pre>
       * 4 to 9 x
       * </pre>
       *
       * <code>.SearchRequest.Sort sort = 10;</code>
       */
      public Builder setSortValue(int value) {
        sort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 4 to 9 x
       * </pre>
       *
       * <code>.SearchRequest.Sort sort = 10;</code>
       */
      public com.example.SearchRequestProto.SearchRequest.Sort getSort() {
        @SuppressWarnings("deprecation")
        com.example.SearchRequestProto.SearchRequest.Sort result = com.example.SearchRequestProto.SearchRequest.Sort.valueOf(sort_);
        return result == null ? com.example.SearchRequestProto.SearchRequest.Sort.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 4 to 9 x
       * </pre>
       *
       * <code>.SearchRequest.Sort sort = 10;</code>
       */
      public Builder setSort(com.example.SearchRequestProto.SearchRequest.Sort value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sort_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 4 to 9 x
       * </pre>
       *
       * <code>.SearchRequest.Sort sort = 10;</code>
       */
      public Builder clearSort() {
        
        sort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:SearchRequest)
    private static final com.example.SearchRequestProto.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.SearchRequestProto.SearchRequest();
    }

    public static com.example.SearchRequestProto.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      @java.lang.Override
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.SearchRequestProto.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SearchRequest.proto\"\200\001\n\rSearchRequest\022" +
      "\017\n\007keyword\030\001 \001(\t\022\014\n\004page\030\002 \001(\005\022\014\n\004size\030\003" +
      " \001(\005\022!\n\004sort\030\n \001(\0162\023.SearchRequest.Sort\"" +
      "\031\n\004Sort\022\007\n\003ASC\020\000\022\010\n\004DESC\020\001J\004\010\004\020\nB!\n\013com." +
      "exampleB\022SearchRequestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new java.lang.String[] { "Keyword", "Page", "Size", "Sort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
